### ISSUE TITLE
User Facing Content

### ISSUE THREAD

**Issue by wdturner** [Patch4747/drg-mods#14]
As a newcomer to DRG and modding, a catalog of available mods in this project and a separate "How to Install Our Mods" guide would greatly improve the usability.

**Comment by wdturner** [comment]
Oh and maybe some quick instructions on how to see the mods. I've only had fester fleas on one mission so far and don't remember where and how to see the mod in action. And maybe how to uninstall mods as well.

**Comment by JoshuaMarion** [comment]
Hey Professor Turner, thank you for trying Deep Rock Galactic! We appreciate your feedback. I have fixed these issues with #15. If you have any questions or concerns, feel free to open more issues!
